add_newline = true
format = "$directory$git_branch$git_status$line_break$character"

[directory]
format = "[$path]($style)"
style = "bold #7aa2ff"
truncation_length = 3
truncate_to_repo = false
home_symbol = "~"
read_only = ""

[git_branch]
format = " [$branch]($style)"
style = "bold #8a8a8a"
symbol = ""

[git_status]
format = "[$all_status]($style)"
style = "bold #ff79c6"
modified = "*"
conflicted = ""
untracked = ""
stashed = ""
staged = ""
renamed = ""
deleted = ""
ahead = ""
behind = ""
diverged = ""
ignore_submodules = true

[character]
success_symbol = "[❯](bold #b084f5)"
error_symbol = "[❯](bold #ff5555)"
